import argparse
def parser_args():

    parser = argparse.ArgumentParser()
    # ========================= federated learning parameters ========================
    parser.add_argument('--trainTargetModel', type=bool, default=False, help='True:train target model')
    parser.add_argument('--trainShadowModel', type=bool, default=False, help='True:train shadow model')
    parser.add_argument('--num_users', type=int, default=5,help="Total number of clients (K)")
    parser.add_argument('--save_dir', type=str, default='./saved_mia_models', help='Training logs and model save root path')
    parser.add_argument('--log_folder_name', type=str, default='/training_log_correct_iid/',help='Training log subdirectories name')
    parser.add_argument('--samples_per_user', type=int, default=5000,help="Number of data samples per client")
    parser.add_argument('--defense', type=str, default="none", help="Adversarial defense methods, optional: [mix_up, quant, sparse]")
    parser.add_argument('--d_scale', type=float, default=0.0,help="Parameter scale of quant or sparse defense strategy")
    parser.add_argument('--klam', type=int, default=3,help="The k-parameter of Instagram defense scheme")
    parser.add_argument('--up_bound', type=float, default=0.65,help="The upper bound of λ in Instagram")
    parser.add_argument('--mix_alpha', type=float, default=0.01,help="Beta distribution alpha parameter for mix up defense")
    parser.add_argument('--seed', type=int, default=42,help="Global random seed")
    parser.add_argument('--frac', type=float, default=1,help="Proportion of clients participating in each training round (C)")
    parser.add_argument('--local_ep', type=int, default=1,help="Local training rounds per client (E)")
    parser.add_argument('--batch_size', type=int, default=100,help="Batch size for local training (B)")
    parser.add_argument('--lr_outer', type=float, default=1,help="Global learning rate")
    parser.add_argument('--lr', type=float, default=0.01,help="Local updated learning rate")
    parser.add_argument('--lr_up', type=str, default='common',help='Learning rate scheduling strategy: [consensus, milestone, cosine]')
    parser.add_argument('--gamma', type=float, default=0.99,help="Exponential decay coefficient")
    parser.add_argument('--iid', type=int,  default =1,help='Does the data have an IID distribution (1 IID, 0 non IID)')
    parser.add_argument('--beta', type=float, default=1,help='The β parameter of Dirichlet distribution in non IID cases')
    parser.add_argument('--wd', type=float, default=1e-5,help='Weight decay coefficient (L2 regularization)')
    parser.add_argument('--optim', type=str, default='sgd',help='Optimizer type: [sgd, adam]')
    parser.add_argument('--epochs', type=int, default=100,help='Global communication round count')
    parser.add_argument('--sampling_type', choices=['poisson', 'uniform'],default='uniform', type=str,help='Client sampling type')
    parser.add_argument('--data_augment', type=int,  default =0,help='Whether to enable data augmentation (1 enabled, 0 disabled)')
    parser.add_argument('--sampling_proportion', type=float,  default=1.0,help='Client sampling ratio')
    parser.add_argument('--model_name', type=str, default='alexnet', choices=['alexnet','ResNet18'],help='Model Architecture Name')
    parser.add_argument('--dataset', type=str, default='dermnet', help="dataset name")
    parser.add_argument('--data_root', default='./Dataset',help='Root directory of the original dataset')
    parser.add_argument('--num_classes', default=10, type=int,help='Number of categories for classification tasks')
    parser.add_argument('--bp_interval', default=30, type=int, help='Local Backpropagation Interval')
    parser.add_argument('--log_interval', default=1, type=int,help='Interval rounds for evaluating losses and accuracy')
    parser.add_argument('--exp-id', type=int, default=1, help='Experiment Number')
    parser.add_argument("--sigma_sgd",type=float,default=0.0,metavar="S",help="Noise multiplication factor for differential privacy of experimental numbers",)
    parser.add_argument("--grad_norm",type=float,default=1e4,help="Upper limit of single sample gradient clipping norm",)
    parser.add_argument('--dp', action='store_true', default=False,help='Whether to enable differential privacy')
    parser.add_argument('--sigma',  type=float, default= 0.1 , help='Gaussian noise standard deviation')
    args = parser.parse_args()

    return args
